variables:
  SONAR_TOKEN: $SONAR_TOKEN
  SONAR_HOST_URL: $SONAR_HOST_URL
  GIT_DEPTH: 0
stages:
  - test
sonarqube-check:
  image: sonarsource/sonar-scanner-cli:4.4
  stage: test
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: false
  # when: manual
  only:
    # - manual
    - merge_requests
    #- /^sprint_.*$/
    - pushes


